In [1]:
import numpy as np

In [2]:
rk = np.array([[22,44,55],[77,88,99],[74,41,85]])

In [3]:
rk

array([[22, 44, 55],
       [77, 88, 99],
       [74, 41, 85]])

In [4]:
fx = np.array([[56,95,27],[69,82,15],[57,74,35]])

In [5]:
fx

array([[56, 95, 27],
       [69, 82, 15],
       [57, 74, 35]])

In [8]:
print(rk.dtype)

int32


In [9]:
rk * fx

array([[1232, 4180, 1485],
       [5313, 7216, 1485],
       [4218, 3034, 2975]])

In [10]:
rk + fx

array([[ 78, 139,  82],
       [146, 170, 114],
       [131, 115, 120]])

In [11]:
rk

array([[22, 44, 55],
       [77, 88, 99],
       [74, 41, 85]])

In [12]:
print(rk[:,-1])

[55 99 85]


In [14]:
print(rk[:,1])

[44 88 41]


In [16]:
print(rk[1,2])

99


In [18]:
print(rk[1:3,0:2])

[[77 88]
 [74 41]]


In [21]:
print(np.random.randint(1,6+1))

3


In [22]:
print(np.sqrt(rk))

[[4.69041576 6.63324958 7.41619849]
 [8.77496439 9.38083152 9.94987437]
 [8.60232527 6.40312424 9.21954446]]


In [23]:
rk

array([[22, 44, 55],
       [77, 88, 99],
       [74, 41, 85]])

In [24]:
print(np.append(rk,11))

[22 44 55 77 88 99 74 41 85 11]


In [25]:
rk

array([[22, 44, 55],
       [77, 88, 99],
       [74, 41, 85]])

In [27]:
rk = rk.astype("float64")

In [28]:
rk.dtype

dtype('float64')

In [29]:
rk

array([[22., 44., 55.],
       [77., 88., 99.],
       [74., 41., 85.]])